#!/usr/bin/env node
/**
 * Write the fleet into cars.html so it is in the HTML, not only in JavaScript.
 *
 * The catalogue loads its cars from /api/cars after the page renders, and /api/
 * is closed to crawlers. Googlebot runs the JavaScript and sees the cars, but
 * GPTBot, ClaudeBot and PerplexityBot do not, so the one dataset PlusRent owns
 * (which cars, at which price) was invisible to every AI that gets asked where
 * to rent a car in Moldova.
 *
 * This fetches the live fleet and writes a real table between the markers in
 * each language's cars.html, plus an ItemList in JSON-LD. The table is visible
 * to visitors too: it is a price comparison, which the card grid is not. Nothing
 * is hidden from anyone, so there is no cloaking.
 *
 * Run it whenever the fleet changes:  npm run fleet
 */

const fs = require("fs");
const path = require("path");

const API = process.env.FLEET_API || "https://plusrent.md/api/cars";
const PUBLIC = path.join(__dirname, "..", "public");
const START = "<!-- FLEET-TABLE:START (generated by scripts/render-fleet.js, do not edit by hand) -->";
const END = "<!-- FLEET-TABLE:END -->";

const { fleetSection, fleetItemList } = require("../lib/render-fleet-table");

// the markup itself lives in lib/ so the server route renders exactly the same
const table = (cars, lang) =>
  [START, fleetSection(cars, lang), "\n      ", END].join("");
const itemList = fleetItemList;

function lowest(car) {
  let p = car.price_policy;
  if (typeof p === "string") { try { p = JSON.parse(p); } catch { p = {}; } }
  const vals = Object.values(p || {}).map(parseFloat).filter(Number.isFinite);
  return vals.length ? Math.min(...vals) : null;
}

async function main() {
  const res = await fetch(API);
  if (!res.ok) throw new Error(`${API} returned ${res.status}`);
  let cars = await res.json();
  if (!Array.isArray(cars)) throw new Error("unexpected API shape");

  // Show them in the order the dashboard sets, cheapest first inside that.
  cars.sort((a, b) => {
    const d = (a.display_order ?? 999) - (b.display_order ?? 999);
    if (d) return d;
    return (lowest(a) ?? 1e9) - (lowest(b) ?? 1e9);
  });
  console.log(`fetched ${cars.length} cars from ${API}`);

  for (const lang of ["ro", "ru", "en"]) {
    const file = path.join(PUBLIC, lang, "cars.html");
    let html = fs.readFileSync(file, "utf8");
    const nl = html.includes("\r\n") ? "\r\n" : "\n";

    const block = table(cars, lang).replace(/\n/g, nl);
    const s = html.indexOf(START);
    const e = html.indexOf(END);
    if (s === -1 || e === -1) {
      console.error(`  ${lang}: markers missing, skipped`);
      continue;
    }
    html = html.slice(0, s) + block + html.slice(e + END.length);

    // the machine-readable copy of the same table
    const ldStart = `<script type="application/ld+json" id="fleet-itemlist">`;
    const ldEnd = `</script>`;
    const ld = ldStart + nl + JSON.stringify(itemList(cars, lang), null, 2).replace(/\n/g, nl) + nl + ldEnd;
    const li = html.indexOf(ldStart);
    if (li === -1) {
      html = html.replace("</head>", "  " + ld + nl + "</head>");
    } else {
      const le = html.indexOf(ldEnd, li) + ldEnd.length;
      html = html.slice(0, li) + ld + html.slice(le);
    }

    fs.writeFileSync(file, html);
    console.log(`  ${lang}: wrote ${cars.length} cars`);
  }
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
