#!/usr/bin/env node
/**
 * Write the fleet into cars.html so it is in the HTML, not only in JavaScript.
 *
 * The catalogue loads its cars from /api/cars after the page renders, and /api/
 * is closed to crawlers. Googlebot runs the JavaScript and sees the cars, but
 * GPTBot, ClaudeBot and PerplexityBot do not, so the one dataset PlusRent owns
 * (which cars, at which price) was invisible to every AI that gets asked where
 * to rent a car in Moldova.
 *
 * This fetches the live fleet and writes a real table between the markers in
 * each language's cars.html, plus an ItemList in JSON-LD. The table is visible
 * to visitors too: it is a price comparison, which the card grid is not. Nothing
 * is hidden from anyone, so there is no cloaking.
 *
 * Run it whenever the fleet changes:  npm run fleet
 */

const fs = require("fs");
const path = require("path");

const API = process.env.FLEET_API || "https://plusrent.md/api/cars";
const PUBLIC = path.join(__dirname, "..", "public");
const START = "<!-- FLEET-TABLE:START (generated by scripts/render-fleet.js, do not edit by hand) -->";
const END = "<!-- FLEET-TABLE:END -->";

const T = {
  ro: {
    heading: "Flota și tarifele pe zi",
    intro: "Tarifele scad cu numărul de zile. RCA și 200 km pe zi sunt incluse, fără avans.",
    car: "Mașina", year: "An", type: "Tip", gear: "Cutie", fuel: "Combustibil",
    seats: "Locuri", d12: "1 la 2 zile", d37: "3 la 7 zile", d820: "8 la 20 zile",
    d2145: "21 la 45 zile", d46: "46+ zile", perday: "pe zi",
    unavailable: "rezervată acum", updated: "Tarife actualizate la",
    cta: "Vezi mașina", auto: "Automată", manual: "Manuală",
  },
  ru: {
    heading: "Автопарк и цены за сутки",
    intro: "Чем больше суток, тем ниже цена. Страховка RCA и 200 км в сутки включены, без предоплаты.",
    car: "Машина", year: "Год", type: "Тип", gear: "Коробка", fuel: "Топливо",
    seats: "Мест", d12: "1 до 2 суток", d37: "3 до 7 суток", d820: "8 до 20 суток",
    d2145: "21 до 45 суток", d46: "46+ суток", perday: "в сутки",
    unavailable: "сейчас занята", updated: "Цены обновлены",
    cta: "Смотреть", auto: "Автомат", manual: "Механика",
  },
  en: {
    heading: "The fleet and the daily rates",
    intro: "The rate drops with the number of days. Insurance and 200 km a day are included, no deposit up front.",
    car: "Car", year: "Year", type: "Type", gear: "Gearbox", fuel: "Fuel",
    seats: "Seats", d12: "1 to 2 days", d37: "3 to 7 days", d820: "8 to 20 days",
    d2145: "21 to 45 days", d46: "46+ days", perday: "per day",
    unavailable: "booked right now", updated: "Rates updated",
    cta: "See the car", auto: "Automatic", manual: "Manual",
  },
};

// The API stores these in English; the page has to read in its own language.
const WORDS = {
  fuel: {
    gasoline: { ro: "Benzină", ru: "Бензин", en: "Petrol" },
    petrol: { ro: "Benzină", ru: "Бензин", en: "Petrol" },
    diesel: { ro: "Motorină", ru: "Дизель", en: "Diesel" },
    hybrid: { ro: "Hibrid", ru: "Гибрид", en: "Hybrid" },
    electric: { ro: "Electric", ru: "Электро", en: "Electric" },
    gas: { ro: "Gaz", ru: "Газ", en: "LPG" },
  },
  type: {
    sedan: { ro: "Sedan", ru: "Седан", en: "Sedan" },
    crossover: { ro: "Crossover", ru: "Кроссовер", en: "Crossover" },
    suv: { ro: "SUV", ru: "Внедорожник", en: "SUV" },
    hatchback: { ro: "Hatchback", ru: "Хэтчбек", en: "Hatchback" },
    minivan: { ro: "Minivan", ru: "Минивэн", en: "Minivan" },
    universal: { ro: "Break", ru: "Универсал", en: "Estate" },
    coupe: { ro: "Coupe", ru: "Купе", en: "Coupe" },
  },
};

function word(group, value, lang) {
  if (!value) return "-";
  const hit = WORDS[group][String(value).toLowerCase().trim()];
  return hit ? hit[lang] : value;
}

const esc = (s) =>
  String(s == null ? "" : s)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

function policy(car) {
  let p = car.price_policy;
  if (typeof p === "string") { try { p = JSON.parse(p); } catch { p = {}; } }
  return p || {};
}

const price = (p, k) => {
  const v = parseFloat(p[k]);
  return isFinite(v) ? v : null;
};

function lowest(car) {
  const vals = Object.values(policy(car)).map(parseFloat).filter(isFinite);
  return vals.length ? Math.min(...vals) : null;
}

function gearLabel(car, t) {
  const g = String(car.gear_type || "").toLowerCase();
  if (g.startsWith("auto")) return t.auto;
  if (g.startsWith("man")) return t.manual;
  return car.gear_type || "-";
}

function table(cars, lang) {
  const t = T[lang];
  const today = new Date().toISOString().slice(0, 10);
  const rows = cars.map((car) => {
    const p = policy(car);
    const name = `${car.make_name || ""} ${car.model_name || ""}`.trim();
    const cell = (k) => {
      const v = price(p, k);
      return v === null ? "<td>-</td>" : `<td>&euro;${v}</td>`;
    };
    return `
        <tr>
          <th scope="row">${esc(name)}${car.booked ? ` <span class="pr-fleet-busy">${esc(t.unavailable)}</span>` : ""}</th>
          <td>${esc(car.production_year || "-")}</td>
          <td>${esc(word("type", car.car_type, lang))}</td>
          <td>${esc(gearLabel(car, t))}</td>
          <td>${esc(word("fuel", car.fuel_type, lang))}</td>
          <td>${esc(car.num_passengers || "-")}</td>
          ${cell("1-2")}
          ${cell("3-7")}
          ${cell("8-20")}
          ${cell("21-45")}
          ${cell("46+")}
        </tr>`;
  }).join("");

  return `${START}
      <section class="pr-fleet-table-section" aria-labelledby="pr-fleet-heading">
        <h2 id="pr-fleet-heading">${esc(t.heading)}</h2>
        <p class="pr-fleet-intro">${esc(t.intro)}</p>
        <div class="pr-fleet-scroll">
          <table class="pr-fleet-table">
            <caption class="pr-fleet-caption">${esc(t.updated)} ${today}</caption>
            <thead>
              <tr>
                <th scope="col">${esc(t.car)}</th>
                <th scope="col">${esc(t.year)}</th>
                <th scope="col">${esc(t.type)}</th>
                <th scope="col">${esc(t.gear)}</th>
                <th scope="col">${esc(t.fuel)}</th>
                <th scope="col">${esc(t.seats)}</th>
                <th scope="col">${esc(t.d12)}</th>
                <th scope="col">${esc(t.d37)}</th>
                <th scope="col">${esc(t.d820)}</th>
                <th scope="col">${esc(t.d2145)}</th>
                <th scope="col">${esc(t.d46)}</th>
              </tr>
            </thead>
            <tbody>${rows}
            </tbody>
          </table>
        </div>
      </section>
      ${END}`;
}

function itemList(cars, lang) {
  const items = cars.map((car, i) => {
    const name = `${car.make_name || ""} ${car.model_name || ""}`.trim();
    const low = lowest(car);
    const node = {
      "@type": "ListItem",
      position: i + 1,
      item: {
        "@type": "Car",
        name,
        vehicleModelDate: String(car.production_year || ""),
        bodyType: car.car_type || undefined,
        fuelType: car.fuel_type || undefined,
        vehicleTransmission: car.gear_type || undefined,
        seatingCapacity: car.num_passengers || undefined,
        numberOfDoors: car.num_doors || undefined,
        brand: { "@type": "Brand", name: car.make_name || "" },
      },
    };
    if (low !== null) {
      node.item.offers = {
        "@type": "Offer",
        price: String(low),
        priceCurrency: "EUR",
        availability: car.booked
          ? "https://schema.org/OutOfStock"
          : "https://schema.org/InStock",
        priceSpecification: {
          "@type": "UnitPriceSpecification",
          price: String(low),
          priceCurrency: "EUR",
          unitCode: "DAY",
        },
        seller: { "@id": "https://plusrent.md/#business" },
      };
    }
    return node;
  });

  const url =
    lang === "ro" ? "https://plusrent.md/ro/cars"
    : lang === "ru" ? "https://plusrent.md/ru/cars"
    : "https://plusrent.md/en/cars";

  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    "@id": url + "#fleet",
    name: T[lang].heading,
    numberOfItems: cars.length,
    itemListElement: items,
  };
}

async function main() {
  const res = await fetch(API);
  if (!res.ok) throw new Error(`${API} returned ${res.status}`);
  let cars = await res.json();
  if (!Array.isArray(cars)) throw new Error("unexpected API shape");

  // Show them in the order the dashboard sets, cheapest first inside that.
  cars.sort((a, b) => {
    const d = (a.display_order ?? 999) - (b.display_order ?? 999);
    if (d) return d;
    return (lowest(a) ?? 1e9) - (lowest(b) ?? 1e9);
  });
  console.log(`fetched ${cars.length} cars from ${API}`);

  for (const lang of ["ro", "ru", "en"]) {
    const file = path.join(PUBLIC, lang, "cars.html");
    let html = fs.readFileSync(file, "utf8");
    const nl = html.includes("\r\n") ? "\r\n" : "\n";

    const block = table(cars, lang).replace(/\n/g, nl);
    const s = html.indexOf(START);
    const e = html.indexOf(END);
    if (s === -1 || e === -1) {
      console.error(`  ${lang}: markers missing, skipped`);
      continue;
    }
    html = html.slice(0, s) + block + html.slice(e + END.length);

    // the machine-readable copy of the same table
    const ldStart = `<script type="application/ld+json" id="fleet-itemlist">`;
    const ldEnd = `</script>`;
    const ld = ldStart + nl + JSON.stringify(itemList(cars, lang), null, 2).replace(/\n/g, nl) + nl + ldEnd;
    const li = html.indexOf(ldStart);
    if (li === -1) {
      html = html.replace("</head>", "  " + ld + nl + "</head>");
    } else {
      const le = html.indexOf(ldEnd, li) + ldEnd.length;
      html = html.slice(0, li) + ld + html.slice(le);
    }

    fs.writeFileSync(file, html);
    console.log(`  ${lang}: wrote ${cars.length} cars`);
  }
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
